# Generated by Django 4.1.7 on 2023-03-08 02:36

from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.TextField()),
                ('description', models.TextField(default='This is an awesomeproduct')),
                ('image', models.ImageField(default=None, storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to='')),
                ('altname', models.CharField(default='image', max_length=100)),
            ],
        ),
    ]
